#!/bin/sh
CURRENT_DIR="$(dirname "$0")"
LOG_FILE="$TEMP/somombo/updater/status.log"; mkdir -p "$(dirname $LOG_FILE)";
VERSION=$(cat "$CURRENT_DIR/VERSION")

source "$CURRENT_DIR/params.sh"

err_code=1

echo
echo ">>> 1. Updating Nodejs and NPM <<<"
echo

choco upgrade nodejs-lts --yes
if [ $? -ne 0 ]; then err_code=$(($err_code * 2)); fi

npm-windows-upgrade --no-spinner --version=latest
if [ $? -ne 0 ]; then err_code=$(($err_code * 3)); fi

npm update --global
if [ $? -ne 0 ]; then err_code=$(($err_code * 5)); fi


echo
echo ">>> 2. Updating Conda <<<"
echo

choco upgrade miniconda3 --yes
if [ $? -ne 0 ]; then err_code=$(($err_code * 7)); fi

CONDA_ROOT="/c/tools/miniconda3" #TODO: Somo> Find a way to not depend on hard coded $CONDA_ROOT path
source "$CONDA_ROOT/Scripts/activate"
if [ $? -ne 0 ]; then err_code=$(($err_code * 11)); fi
	
	conda update --name=root conda --yes
	if [ $? -ne 0 ]; then err_code=$(($err_code * 13)); fi

	conda update --all --yes
	if [ $? -ne 0 ]; then err_code=$(($err_code * 17)); fi

	conda install console_shortcut powershell_shortcut --yes
	if [ $? -ne 0 ]; then err_code=$(($err_code * 19)); fi

conda deactivate
if [ $? -ne 0 ]; then err_code=$(($err_code * 23)); fi

echo	
echo ">>> 3. Updating the rest of the Choco packages <<<"
echo

choco upgrade all --yes
if [ $? -ne 0 ]; then err_code=$(($err_code * 29)); fi

echo	
echo ">>> 4. Updating wsl apt packages <<<"
echo

wsl --user root --exec sh -c "apt-get update -y && apt-get upgrade -y"
if [ $? -ne 0 ]; then err_code=$(($err_code * 31)); fi

######################### Results ########################

if [ $err_code -ne 1 ]; then
    echo "$(date) |> FAIED with Error Code: $err_code" >> $LOG_FILE
    exit $err_code
else
    echo "$(date) |> SUCCESS" >> $LOG_FILE
fi


"$CURRENT_DIR/upd" --log | grep -e "\S"
echo